# Generated by Django 3.0.2 on 2020-02-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack_quiz', '0002_auto_20200205_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizuser',
            name='avatar',
        ),
    ]
