# Generated by Django 3.0.2 on 2020-02-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack_quiz', '0004_quiz_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
    ]
