# Generated by Django 3.0.2 on 2020-04-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack_quiz', '0006_auto_20200324_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='answer_text',
            field=models.TextField(default='answer text goes here'),
        ),
    ]
