# Generated by Django 3.0.2 on 2020-04-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack_quiz', '0008_auto_20200420_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('high_score_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=25)),
                ('user_correct_score', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='quiz_id',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='QuizUser',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
