# Generated by Django 3.0.2 on 2020-04-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack_quiz', '0009_auto_20200427_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='display_name',
            field=models.CharField(default='Anonymous', max_length=25, null=True),
        ),
    ]
