# Generated by Django 3.0.2 on 2020-04-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack_quiz', '0010_auto_20200428_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='user_correct_score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
