# Generated by Django 3.0.2 on 2020-04-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack_quiz', '0011_auto_20200429_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='display_name',
            field=models.CharField(default='Anonymous', max_length=25),
        ),
        migrations.AlterField(
            model_name='highscore',
            name='user_correct_score',
            field=models.IntegerField(default=-1),
        ),
    ]
