# Generated by Django 3.0.2 on 2020-05-15 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack_quiz', '0012_auto_20200429_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='quiz_id',
            new_name='associated_quiz_id',
        ),
        migrations.AddField(
            model_name='highscore',
            name='associated_quiz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fullstack_quiz.Quiz'),
        ),
    ]
