# Generated by Django 3.0.2 on 2020-05-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack_quiz', '0014_auto_20200520_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='correct_choice',
            field=models.CharField(default='choiceIndexX', max_length=50),
        ),
    ]
